name: Build Yocto AWS Demo

on:
  workflow_dispatch:

env:
  CACHE_DIR: $GITHUB_WORKSPACE/gh-runners/quic-yocto
  KAS_REPO_REF_DIR: $GITHUB_WORKSPACE/gh-runners/quic-yocto/kas-mirrors
  AWS_BUILD_HOST: codebuild-qComHweDemo-${{ github.run_id }}

jobs:
  kas-lock:
    if: github.repository == 'sampra2025/meta-qcom-hwe-ci-test'
    runs-on: 
      - codebuild-qComHweDemo-${{ github.run_id }}-${{ github.run_attempt }}
      
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run kas lock
        run: |
          kas dump --update --lock --inplace ci/base.yml

      - uses: actions/upload-artifact@v4
        with:
          name: kas-lock
          path: ci/*.lock.yml

  yocto-check-layer:
    needs: kas-lock
    if: github.repository == 'sampra2025/meta-qcom-hwe-ci-test'
    runs-on: 
      - codebuild-qComHweDemo-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/download-artifact@v4
        with:
          name: kas-lock
          path: ci/

      - name: Run yocto-check-layer
        run: |
          ci/yocto-check-layer.sh

  yocto-patchreview:
    needs: kas-lock
    if: github.repository == 'sampra2025/meta-qcom-hwe-ci-test'
    runs-on: 
      - codebuild-qComHweDemo-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/download-artifact@v4
        with:
          name: kas-lock
          path: ci/

      - name: Run Yocto patchreview
        run: |
          ci/yocto-patchreview.sh

  compile:
    needs: kas-lock
    if: github.repository == 'sampra2025/meta-qcom-hwe-ci-test'
    strategy:
      fail-fast: true
      matrix:
        machine:
          - qcs6490-rb3gen2-core-kit
          - sa8775p-ride-sx
    runs-on: 
      - codebuild-qComHweDemo-${{ github.run_id }}-${{ github.run_attempt }}
    name: ${{ matrix.machine }}/poky/systemd
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/download-artifact@v4
        with:
          name: kas-lock
          path: ci/

      - name: Kas build
        run: |
          whoami; id
          export DL_DIR=${CACHE_DIR}/downloads
          export SSTATE_DIR=${CACHE_DIR}/sstate-cache
          export KAS_WORK_DIR=$PWD/../kas
          mkdir $KAS_WORK_DIR
          kas build ci/mirror.yml:ci/${{ matrix.machine }}.yml

      - name: Publish image
        run: |
          build_dir=${CACHE_DIR}/builds/${GITHUB_RUN_ID}
          mkdir -p $build_dir
          img_dir=$build_dir/${{ matrix.machine }}
          [ -d $img_dir ] && rm -rf $img_dir
          mv ../kas/build/tmp/deploy/images/${{matrix.machine}} $img_dir

          # Instruct our file server to make these files available for download         

  create-output:
    needs: compile
    outputs:
      url: ${{ steps.print-output.outputs.url }}
    runs-on: 
      - codebuild-qComHweDemo-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - name: "Print output"
        id: print-output
        run: |
          echo "Downloads URL: https://quic-yocto-fileserver-1029608027416.us-central1.run.app/${GITHUB_RUN_ID}/"
          echo "url=\"https://quic-yocto-fileserver-1029608027416.us-central1.run.app/${GITHUB_RUN_ID}/\"" >> $GITHUB_OUTPUT
